services:
  example:
    image: ${EXAMPLE_IMAGE:-nginx:alpine}
    container_name: example
    restart: unless-stopped
    ports:
      - ${EXAMPLE_PORT:-8080}:80
    environment:
      - FOO=${EXAMPLE_FOO:-default}
    volumes:
      - ./data:/usr/share/nginx/html:ro
